/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PkiRouteImport } from './routes/pki'
import { Route as CyberfoundationsIndexRouteImport } from './routes/cyberfoundations.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PkiRoute = PkiRouteImport.update({
  id: '/pki',
  path: '/pki',
  getParentRoute: () => rootRouteImport,
} as any)
const CyberfoundationsIndexRoute = CyberfoundationsIndexRouteImport.update({
  id: '/cyberfoundations/',
  path: '/cyberfoundations/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pki': typeof PkiRoute
  '/cyberfoundations/': typeof CyberfoundationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pki': typeof PkiRoute
  '/cyberfoundations': typeof CyberfoundationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pki': typeof PkiRoute
  '/cyberfoundations/': typeof CyberfoundationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pki' | '/cyberfoundations/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pki' | '/cyberfoundations'
  id: '__root__' | '/' | '/pki' | '/cyberfoundations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PkiRoute: typeof PkiRoute
  CyberfoundationsIndexRoute: typeof CyberfoundationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pki': {
      id: '/pki'
      path: '/pki'
      fullPath: '/pki'
      preLoaderRoute: typeof PkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyberfoundations/': {
      id: '/cyberfoundations/'
      path: '/cyberfoundations'
      fullPath: '/cyberfoundations/'
      preLoaderRoute: typeof CyberfoundationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PkiRoute: PkiRoute,
  CyberfoundationsIndexRoute: CyberfoundationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
