/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as InstructorRouteImport } from './routes/instructor'
import { Route as Phase3ConsoleRouteImport } from './routes/phase3-console'
import { Route as Phase3GradingRouteImport } from './routes/phase3-grading'
import { Route as PkiRouteImport } from './routes/pki'
import { Route as CyberfoundationsIndexRouteImport } from './routes/cyberfoundations.index'
import { Route as PkiIndexRouteImport } from './routes/pki.index'
import { Route as PkiCapstoneRouteImport } from './routes/pki.capstone'
import { Route as PkiPhase3RouteImport } from './routes/pki.phase3'
import { Route as CyberfoundationsWeek06FromTheGridToCloudHeightsRouteImport } from './routes/cyberfoundations.week-06.from-the-grid-to-cloud-heights'
import { Route as CyberfoundationsWeek07CloudHeightsGuardPostRouteImport } from './routes/cyberfoundations.week-07.cloud-heights-guard-post'
import { Route as PkiCapstoneIndexRouteImport } from './routes/pki.capstone.index'
import { Route as PkiCapstoneStageRouteImport } from './routes/pki.capstone.$stage'
import { Route as PkiCapstoneEvidenceRouteImport } from './routes/pki.capstone.evidence'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRoute = InstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const Phase3ConsoleRoute = Phase3ConsoleRouteImport.update({
  id: '/phase3-console',
  path: '/phase3-console',
  getParentRoute: () => rootRouteImport,
} as any)
const Phase3GradingRoute = Phase3GradingRouteImport.update({
  id: '/phase3-grading',
  path: '/phase3-grading',
  getParentRoute: () => rootRouteImport,
} as any)
const PkiRoute = PkiRouteImport.update({
  id: '/pki',
  path: '/pki',
  getParentRoute: () => rootRouteImport,
} as any)
const CyberfoundationsIndexRoute = CyberfoundationsIndexRouteImport.update({
  id: '/cyberfoundations/',
  path: '/cyberfoundations/',
  getParentRoute: () => rootRouteImport,
} as any)
const PkiIndexRoute = PkiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PkiRoute,
} as any)
const PkiCapstoneRoute = PkiCapstoneRouteImport.update({
  id: '/capstone',
  path: '/capstone',
  getParentRoute: () => PkiRoute,
} as any)
const PkiPhase3Route = PkiPhase3RouteImport.update({
  id: '/phase3',
  path: '/phase3',
  getParentRoute: () => PkiRoute,
} as any)
const CyberfoundationsWeek06FromTheGridToCloudHeightsRoute =
  CyberfoundationsWeek06FromTheGridToCloudHeightsRouteImport.update({
    id: '/cyberfoundations/week-06/from-the-grid-to-cloud-heights',
    path: '/cyberfoundations/week-06/from-the-grid-to-cloud-heights',
    getParentRoute: () => rootRouteImport,
  } as any)
const CyberfoundationsWeek07CloudHeightsGuardPostRoute =
  CyberfoundationsWeek07CloudHeightsGuardPostRouteImport.update({
    id: '/cyberfoundations/week-07/cloud-heights-guard-post',
    path: '/cyberfoundations/week-07/cloud-heights-guard-post',
    getParentRoute: () => rootRouteImport,
  } as any)
const PkiCapstoneIndexRoute = PkiCapstoneIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PkiCapstoneRoute,
} as any)
const PkiCapstoneStageRoute = PkiCapstoneStageRouteImport.update({
  id: '/$stage',
  path: '/$stage',
  getParentRoute: () => PkiCapstoneRoute,
} as any)
const PkiCapstoneEvidenceRoute = PkiCapstoneEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => PkiCapstoneRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/instructor': typeof InstructorRoute
  '/phase3-console': typeof Phase3ConsoleRoute
  '/phase3-grading': typeof Phase3GradingRoute
  '/pki': typeof PkiRouteWithChildren
  '/pki/capstone': typeof PkiCapstoneRouteWithChildren
  '/pki/phase3': typeof PkiPhase3Route
  '/cyberfoundations/': typeof CyberfoundationsIndexRoute
  '/pki/': typeof PkiIndexRoute
  '/cyberfoundations/week-06/from-the-grid-to-cloud-heights': typeof CyberfoundationsWeek06FromTheGridToCloudHeightsRoute
  '/cyberfoundations/week-07/cloud-heights-guard-post': typeof CyberfoundationsWeek07CloudHeightsGuardPostRoute
  '/pki/capstone/$stage': typeof PkiCapstoneStageRoute
  '/pki/capstone/evidence': typeof PkiCapstoneEvidenceRoute
  '/pki/capstone/': typeof PkiCapstoneIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/instructor': typeof InstructorRoute
  '/phase3-console': typeof Phase3ConsoleRoute
  '/phase3-grading': typeof Phase3GradingRoute
  '/pki/phase3': typeof PkiPhase3Route
  '/cyberfoundations': typeof CyberfoundationsIndexRoute
  '/pki': typeof PkiIndexRoute
  '/cyberfoundations/week-06/from-the-grid-to-cloud-heights': typeof CyberfoundationsWeek06FromTheGridToCloudHeightsRoute
  '/cyberfoundations/week-07/cloud-heights-guard-post': typeof CyberfoundationsWeek07CloudHeightsGuardPostRoute
  '/pki/capstone/$stage': typeof PkiCapstoneStageRoute
  '/pki/capstone/evidence': typeof PkiCapstoneEvidenceRoute
  '/pki/capstone': typeof PkiCapstoneIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/instructor': typeof InstructorRoute
  '/phase3-console': typeof Phase3ConsoleRoute
  '/phase3-grading': typeof Phase3GradingRoute
  '/pki': typeof PkiRouteWithChildren
  '/pki/capstone': typeof PkiCapstoneRouteWithChildren
  '/pki/phase3': typeof PkiPhase3Route
  '/cyberfoundations/': typeof CyberfoundationsIndexRoute
  '/pki/': typeof PkiIndexRoute
  '/cyberfoundations/week-06/from-the-grid-to-cloud-heights': typeof CyberfoundationsWeek06FromTheGridToCloudHeightsRoute
  '/cyberfoundations/week-07/cloud-heights-guard-post': typeof CyberfoundationsWeek07CloudHeightsGuardPostRoute
  '/pki/capstone/$stage': typeof PkiCapstoneStageRoute
  '/pki/capstone/evidence': typeof PkiCapstoneEvidenceRoute
  '/pki/capstone/': typeof PkiCapstoneIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/instructor'
    | '/phase3-console'
    | '/phase3-grading'
    | '/pki'
    | '/pki/capstone'
    | '/pki/phase3'
    | '/cyberfoundations/'
    | '/pki/'
    | '/cyberfoundations/week-06/from-the-grid-to-cloud-heights'
    | '/cyberfoundations/week-07/cloud-heights-guard-post'
    | '/pki/capstone/$stage'
    | '/pki/capstone/evidence'
    | '/pki/capstone/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/instructor'
    | '/phase3-console'
    | '/phase3-grading'
    | '/pki/phase3'
    | '/cyberfoundations'
    | '/pki'
    | '/cyberfoundations/week-06/from-the-grid-to-cloud-heights'
    | '/cyberfoundations/week-07/cloud-heights-guard-post'
    | '/pki/capstone/$stage'
    | '/pki/capstone/evidence'
    | '/pki/capstone'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/instructor'
    | '/phase3-console'
    | '/phase3-grading'
    | '/pki'
    | '/pki/capstone'
    | '/pki/phase3'
    | '/cyberfoundations/'
    | '/pki/'
    | '/cyberfoundations/week-06/from-the-grid-to-cloud-heights'
    | '/cyberfoundations/week-07/cloud-heights-guard-post'
    | '/pki/capstone/$stage'
    | '/pki/capstone/evidence'
    | '/pki/capstone/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  InstructorRoute: typeof InstructorRoute
  Phase3ConsoleRoute: typeof Phase3ConsoleRoute
  Phase3GradingRoute: typeof Phase3GradingRoute
  PkiRoute: typeof PkiRouteWithChildren
  CyberfoundationsIndexRoute: typeof CyberfoundationsIndexRoute
  CyberfoundationsWeek06FromTheGridToCloudHeightsRoute: typeof CyberfoundationsWeek06FromTheGridToCloudHeightsRoute
  CyberfoundationsWeek07CloudHeightsGuardPostRoute: typeof CyberfoundationsWeek07CloudHeightsGuardPostRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phase3-console': {
      id: '/phase3-console'
      path: '/phase3-console'
      fullPath: '/phase3-console'
      preLoaderRoute: typeof Phase3ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phase3-grading': {
      id: '/phase3-grading'
      path: '/phase3-grading'
      fullPath: '/phase3-grading'
      preLoaderRoute: typeof Phase3GradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pki': {
      id: '/pki'
      path: '/pki'
      fullPath: '/pki'
      preLoaderRoute: typeof PkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyberfoundations/': {
      id: '/cyberfoundations/'
      path: '/cyberfoundations'
      fullPath: '/cyberfoundations/'
      preLoaderRoute: typeof CyberfoundationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pki/': {
      id: '/pki/'
      path: '/'
      fullPath: '/pki/'
      preLoaderRoute: typeof PkiIndexRouteImport
      parentRoute: typeof PkiRoute
    }
    '/pki/capstone': {
      id: '/pki/capstone'
      path: '/capstone'
      fullPath: '/pki/capstone'
      preLoaderRoute: typeof PkiCapstoneRouteImport
      parentRoute: typeof PkiRoute
    }
    '/pki/phase3': {
      id: '/pki/phase3'
      path: '/phase3'
      fullPath: '/pki/phase3'
      preLoaderRoute: typeof PkiPhase3RouteImport
      parentRoute: typeof PkiRoute
    }
    '/cyberfoundations/week-06/from-the-grid-to-cloud-heights': {
      id: '/cyberfoundations/week-06/from-the-grid-to-cloud-heights'
      path: '/cyberfoundations/week-06/from-the-grid-to-cloud-heights'
      fullPath: '/cyberfoundations/week-06/from-the-grid-to-cloud-heights'
      preLoaderRoute: typeof CyberfoundationsWeek06FromTheGridToCloudHeightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyberfoundations/week-07/cloud-heights-guard-post': {
      id: '/cyberfoundations/week-07/cloud-heights-guard-post'
      path: '/cyberfoundations/week-07/cloud-heights-guard-post'
      fullPath: '/cyberfoundations/week-07/cloud-heights-guard-post'
      preLoaderRoute: typeof CyberfoundationsWeek07CloudHeightsGuardPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pki/capstone/': {
      id: '/pki/capstone/'
      path: '/'
      fullPath: '/pki/capstone/'
      preLoaderRoute: typeof PkiCapstoneIndexRouteImport
      parentRoute: typeof PkiCapstoneRoute
    }
    '/pki/capstone/$stage': {
      id: '/pki/capstone/$stage'
      path: '/$stage'
      fullPath: '/pki/capstone/$stage'
      preLoaderRoute: typeof PkiCapstoneStageRouteImport
      parentRoute: typeof PkiCapstoneRoute
    }
    '/pki/capstone/evidence': {
      id: '/pki/capstone/evidence'
      path: '/evidence'
      fullPath: '/pki/capstone/evidence'
      preLoaderRoute: typeof PkiCapstoneEvidenceRouteImport
      parentRoute: typeof PkiCapstoneRoute
    }
  }
}

interface PkiCapstoneRouteChildren {
  PkiCapstoneStageRoute: typeof PkiCapstoneStageRoute
  PkiCapstoneEvidenceRoute: typeof PkiCapstoneEvidenceRoute
  PkiCapstoneIndexRoute: typeof PkiCapstoneIndexRoute
}

const PkiCapstoneRouteChildren: PkiCapstoneRouteChildren = {
  PkiCapstoneStageRoute: PkiCapstoneStageRoute,
  PkiCapstoneEvidenceRoute: PkiCapstoneEvidenceRoute,
  PkiCapstoneIndexRoute: PkiCapstoneIndexRoute,
}

const PkiCapstoneRouteWithChildren = PkiCapstoneRoute._addFileChildren(
  PkiCapstoneRouteChildren,
)

interface PkiRouteChildren {
  PkiCapstoneRoute: typeof PkiCapstoneRouteWithChildren
  PkiPhase3Route: typeof PkiPhase3Route
  PkiIndexRoute: typeof PkiIndexRoute
}

const PkiRouteChildren: PkiRouteChildren = {
  PkiCapstoneRoute: PkiCapstoneRouteWithChildren,
  PkiPhase3Route: PkiPhase3Route,
  PkiIndexRoute: PkiIndexRoute,
}

const PkiRouteWithChildren = PkiRoute._addFileChildren(PkiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  InstructorRoute: InstructorRoute,
  Phase3ConsoleRoute: Phase3ConsoleRoute,
  Phase3GradingRoute: Phase3GradingRoute,
  PkiRoute: PkiRouteWithChildren,
  CyberfoundationsIndexRoute: CyberfoundationsIndexRoute,
  CyberfoundationsWeek06FromTheGridToCloudHeightsRoute:
    CyberfoundationsWeek06FromTheGridToCloudHeightsRoute,
  CyberfoundationsWeek07CloudHeightsGuardPostRoute:
    CyberfoundationsWeek07CloudHeightsGuardPostRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
