/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as InstructorRouteImport } from './routes/instructor'
import { Route as PkiRouteImport } from './routes/pki'
import { Route as CyberfoundationsIndexRouteImport } from './routes/cyberfoundations.index'
import { Route as PkiIndexRouteImport } from './routes/pki.index'
import { Route as PkiCapstoneRouteImport } from './routes/pki.capstone'
import { Route as CyberfoundationsWeek06FromTheGridToCloudHeightsRouteImport } from './routes/cyberfoundations.week-06.from-the-grid-to-cloud-heights'
import { Route as CyberfoundationsWeek07CloudHeightsGuardPostRouteImport } from './routes/cyberfoundations.week-07.cloud-heights-guard-post'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRoute = InstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const PkiRoute = PkiRouteImport.update({
  id: '/pki',
  path: '/pki',
  getParentRoute: () => rootRouteImport,
} as any)
const CyberfoundationsIndexRoute = CyberfoundationsIndexRouteImport.update({
  id: '/cyberfoundations/',
  path: '/cyberfoundations/',
  getParentRoute: () => rootRouteImport,
} as any)
const PkiIndexRoute = PkiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PkiRoute,
} as any)
const PkiCapstoneRoute = PkiCapstoneRouteImport.update({
  id: '/capstone',
  path: '/capstone',
  getParentRoute: () => PkiRoute,
} as any)
const CyberfoundationsWeek06FromTheGridToCloudHeightsRoute =
  CyberfoundationsWeek06FromTheGridToCloudHeightsRouteImport.update({
    id: '/cyberfoundations/week-06/from-the-grid-to-cloud-heights',
    path: '/cyberfoundations/week-06/from-the-grid-to-cloud-heights',
    getParentRoute: () => rootRouteImport,
  } as any)
const CyberfoundationsWeek07CloudHeightsGuardPostRoute =
  CyberfoundationsWeek07CloudHeightsGuardPostRouteImport.update({
    id: '/cyberfoundations/week-07/cloud-heights-guard-post',
    path: '/cyberfoundations/week-07/cloud-heights-guard-post',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/instructor': typeof InstructorRoute
  '/pki': typeof PkiRouteWithChildren
  '/pki/capstone': typeof PkiCapstoneRoute
  '/cyberfoundations/': typeof CyberfoundationsIndexRoute
  '/pki/': typeof PkiIndexRoute
  '/cyberfoundations/week-06/from-the-grid-to-cloud-heights': typeof CyberfoundationsWeek06FromTheGridToCloudHeightsRoute
  '/cyberfoundations/week-07/cloud-heights-guard-post': typeof CyberfoundationsWeek07CloudHeightsGuardPostRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/instructor': typeof InstructorRoute
  '/pki/capstone': typeof PkiCapstoneRoute
  '/cyberfoundations': typeof CyberfoundationsIndexRoute
  '/pki': typeof PkiIndexRoute
  '/cyberfoundations/week-06/from-the-grid-to-cloud-heights': typeof CyberfoundationsWeek06FromTheGridToCloudHeightsRoute
  '/cyberfoundations/week-07/cloud-heights-guard-post': typeof CyberfoundationsWeek07CloudHeightsGuardPostRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/instructor': typeof InstructorRoute
  '/pki': typeof PkiRouteWithChildren
  '/pki/capstone': typeof PkiCapstoneRoute
  '/cyberfoundations/': typeof CyberfoundationsIndexRoute
  '/pki/': typeof PkiIndexRoute
  '/cyberfoundations/week-06/from-the-grid-to-cloud-heights': typeof CyberfoundationsWeek06FromTheGridToCloudHeightsRoute
  '/cyberfoundations/week-07/cloud-heights-guard-post': typeof CyberfoundationsWeek07CloudHeightsGuardPostRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/instructor'
    | '/pki'
    | '/pki/capstone'
    | '/cyberfoundations/'
    | '/pki/'
    | '/cyberfoundations/week-06/from-the-grid-to-cloud-heights'
    | '/cyberfoundations/week-07/cloud-heights-guard-post'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/instructor'
    | '/pki/capstone'
    | '/cyberfoundations'
    | '/pki'
    | '/cyberfoundations/week-06/from-the-grid-to-cloud-heights'
    | '/cyberfoundations/week-07/cloud-heights-guard-post'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/instructor'
    | '/pki'
    | '/pki/capstone'
    | '/cyberfoundations/'
    | '/pki/'
    | '/cyberfoundations/week-06/from-the-grid-to-cloud-heights'
    | '/cyberfoundations/week-07/cloud-heights-guard-post'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  InstructorRoute: typeof InstructorRoute
  PkiRoute: typeof PkiRouteWithChildren
  CyberfoundationsIndexRoute: typeof CyberfoundationsIndexRoute
  CyberfoundationsWeek06FromTheGridToCloudHeightsRoute: typeof CyberfoundationsWeek06FromTheGridToCloudHeightsRoute
  CyberfoundationsWeek07CloudHeightsGuardPostRoute: typeof CyberfoundationsWeek07CloudHeightsGuardPostRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pki': {
      id: '/pki'
      path: '/pki'
      fullPath: '/pki'
      preLoaderRoute: typeof PkiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyberfoundations/': {
      id: '/cyberfoundations/'
      path: '/cyberfoundations'
      fullPath: '/cyberfoundations/'
      preLoaderRoute: typeof CyberfoundationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pki/': {
      id: '/pki/'
      path: '/'
      fullPath: '/pki/'
      preLoaderRoute: typeof PkiIndexRouteImport
      parentRoute: typeof PkiRoute
    }
    '/pki/capstone': {
      id: '/pki/capstone'
      path: '/capstone'
      fullPath: '/pki/capstone'
      preLoaderRoute: typeof PkiCapstoneRouteImport
      parentRoute: typeof PkiRoute
    }
    '/cyberfoundations/week-06/from-the-grid-to-cloud-heights': {
      id: '/cyberfoundations/week-06/from-the-grid-to-cloud-heights'
      path: '/cyberfoundations/week-06/from-the-grid-to-cloud-heights'
      fullPath: '/cyberfoundations/week-06/from-the-grid-to-cloud-heights'
      preLoaderRoute: typeof CyberfoundationsWeek06FromTheGridToCloudHeightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyberfoundations/week-07/cloud-heights-guard-post': {
      id: '/cyberfoundations/week-07/cloud-heights-guard-post'
      path: '/cyberfoundations/week-07/cloud-heights-guard-post'
      fullPath: '/cyberfoundations/week-07/cloud-heights-guard-post'
      preLoaderRoute: typeof CyberfoundationsWeek07CloudHeightsGuardPostRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PkiRouteChildren {
  PkiCapstoneRoute: typeof PkiCapstoneRoute
  PkiIndexRoute: typeof PkiIndexRoute
}

const PkiRouteChildren: PkiRouteChildren = {
  PkiCapstoneRoute: PkiCapstoneRoute,
  PkiIndexRoute: PkiIndexRoute,
}

const PkiRouteWithChildren = PkiRoute._addFileChildren(PkiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  InstructorRoute: InstructorRoute,
  PkiRoute: PkiRouteWithChildren,
  CyberfoundationsIndexRoute: CyberfoundationsIndexRoute,
  CyberfoundationsWeek06FromTheGridToCloudHeightsRoute:
    CyberfoundationsWeek06FromTheGridToCloudHeightsRoute,
  CyberfoundationsWeek07CloudHeightsGuardPostRoute:
    CyberfoundationsWeek07CloudHeightsGuardPostRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
